### ISSUE TITLE
Only restoring cache

### ISSUE THREAD

**Issue by chadtomkiss-madetech** [CircleCI-Public/node-orb#40]
In our pipeline we are installing packages as the first job in the pipeline and then restoring the cache in future jobs.

```
- node/install-packages
```

However, this does a restore cache/install/save cache

I think we only need to restore cache in our future jobs and do not need to run `npm install` again.

Given the cache key is generated automatically, would you advise against manually restoring the cache?

```
node-deps-v1-{{ branch }}-{{ checksum 'package-lock.json' }}
```

![Screenshot 2020-06-30 at 10 49 54](https://user-images.githubusercontent.com/60967748/86112090-74d72c80-babf-11ea-8438-714670920c2f.png)

We would save 30s on our pipeline but not sure if that'd cause any issues.

**Comment by gmemstr** [comment]
This could probably be improved by updating your `package-lock.json` file - since the cache key is based on the commited `package-lock.json`, this is an indication that it is out of date. Using workspaces, rather than relying on our caching, would allow you to share files, including the Node modules, in later jobs in the same workflow https://circleci.com/blog/deep-diving-into-circleci-workspaces
