### ISSUE TITLE
Not working on alpine du to nvm bug

### ISSUE THREAD

**Issue by cedriclombardot** [CircleCI-Public/node-orb#80]
@see https://github.com/nvm-sh/nvm/issues/2059

**Comment by Jaryt** [comment]
Hi! Thank you for your patience. We're working on catching up on our backlog. Since this is a problem with nvm and it being the core command we use to install and manage node versions, we are unable to solve this unless a solution is fixed in npm. We will be sure to keep an eye out and update nvm once they implement as fix.
